name: Update Badges

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.RUST_BADGE }}
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    
    - name: Generate badges
      env:
        GITHUB_TOKEN: ${{ secrets.RUST_BADGE }}
      run: |
        BINARY_NAME=$(find target/release -type f -executable | grep -v '\.d$' | head -n 1)
        echo "Using binary: $BINARY_NAME"
        $BINARY_NAME github janpreet docker-latex docker-latex
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update badges" && git push)